### ISSUE TITLE
cec dependency

### ISSUE THREAD

**Issue by rytilahti** [konikvranik/pyCEC#28]
Requirements.txt doesn't mark cec as a required module, causing the following during the start of homeassistant:
```
Jan 14 05:22:33 rasputin hass[18819]: INFO:homeassistant.bootstrap:Setting up hdmi_cec
Jan 14 05:22:33 rasputin hass[18819]: ERROR:homeassistant.bootstrap:Error during setup of component hdmi_cec
Jan 14 05:22:33 rasputin hass[18819]: Traceback (most recent call last):
Jan 14 05:22:33 rasputin hass[18819]: File "/home/homeassistant/home-assistant/homeassistant/bootstrap.py", line 151, in _async_setup_component
Jan 14 05:22:33 rasputin hass[18819]: None, component.setup, hass, config)
Jan 14 05:22:33 rasputin hass[18819]: File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
Jan 14 05:22:33 rasputin hass[18819]: yield self  # This tells Task to wait for completion.
Jan 14 05:22:33 rasputin hass[18819]: File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
Jan 14 05:22:33 rasputin hass[18819]: value = future.result()
Jan 14 05:22:33 rasputin hass[18819]: File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
Jan 14 05:22:33 rasputin hass[18819]: raise self._exception
Jan 14 05:22:33 rasputin hass[18819]: File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
Jan 14 05:22:33 rasputin hass[18819]: result = self.fn(*self.args, **self.kwargs)
Jan 14 05:22:33 rasputin hass[18819]: File "/home/homeassistant/home-assistant/homeassistant/components/hdmi_cec.py", line 181, in setup
Jan 14 05:22:33 rasputin hass[18819]: adapter = CecAdapter(name="HASS", activate_source=False)
Jan 14 05:22:33 rasputin hass[18819]: File "/home/homeassistant/.homeassistant/deps/pycec/cec.py", line 20, in __init__
Jan 14 05:22:33 rasputin hass[18819]: import cec
Jan 14 05:22:33 rasputin hass[18819]: ImportError: No module named 'cec'
Jan 14 05:22:33 rasputin hass[18819]: INFO:homeassistant.core:Bus:Handling <Event call_service[L]: domain=persistent_notification, service_data=title=Invalid config, notification_id=invalid_config, message=The following components and platforms could not be set up:
Jan 14 05:22:33 rasputin hass[18819]: * [hdmi-cec](https://home-assistant.io/components/hdmi_cec/)
Jan 14 05:22:33 rasputin hass[18819]: Please check your config, service_call_id=1978391600-1, service=create>
```

It also looks like that cec is not python3 compatible: https://github.com/trainman419/python-cec/issues/12

**Comment by happyleavesaoc** [comment]
I think that is actually a different `cec` from the one used in this module. This `cec` is installed by building and installing `libcec` -- it comes with the python 3 bindings.

**Comment by rytilahti** [comment]
Indeed. It's worth to document this somewhere in any case.

**Comment by konikvranik** [comment]
Updated README.md
