### ISSUE TITLE
Shutdown blocking in home-assistant

### ISSUE THREAD

**Issue by konikvranik** [konikvranik/pyCEC#40]

**Comment by konikvranik** [comment]
Exception on restart:
````
led 30 10:52:29 hass hass[14719]: ERROR:homeassistant.core:Error doing job: Future exception was never retrieved
led 30 10:52:29 hass hass[14719]: Traceback (most recent call last):
led 30 10:52:29 hass hass[14719]: File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
led 30 10:52:29 hass hass[14719]: result = self.fn(*self.args, **self.kwargs)
led 30 10:52:29 hass hass[14719]: File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/hdmi_cec.py", line 308, in _shutdown
led 30 10:52:29 hass hass[14719]: hdmi_network.stop()
led 30 10:52:29 hass hass[14719]: File "/home/homeassistant/.homeassistant/deps/pycec/network.py", line 463, in stop
led 30 10:52:29 hass hass[14719]: self._loop.close()
led 30 10:52:29 hass hass[14719]: File "/usr/lib/python3.4/asyncio/unix_events.py", line 52, in close
led 30 10:52:29 hass systemd[1]: Starting Home Assistant for homeassistant...
led 30 10:52:30 hass systemd[1]: Started Home Assistant for homeassistant.
````
