### ISSUE TITLE
pyCEC on a RasPi Zero W "no module cec"

### ISSUE THREAD

**Issue by danito** [konikvranik/pyCEC#46]
Hi,
i've installed libcec and python-libcec (apt-get) and pip(3) install pycec
but when I lauch python(3) -m pycec I get the following:
````
pi@rpihut:~ $ python3 -m pycec
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/pycec/__main__.py", line 164, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/pycec/__main__.py", line 32, in main
    network = HDMINetwork(CecAdapter("pyCEC", activate_source=False),
  File "/usr/local/lib/python3.5/dist-packages/pycec/cec.py", line 20, in __init__
    import cec
ImportError: No module named 'cec'
pi@rpihut:~ $ python -m pycec
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 114, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "/usr/lib/python2.7/runpy.py", line 119, in _get_module_details
    code = loader.get_code(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 283, in get_code
    self.code = compile(source, self.filename, 'exec')
  File "/usr/local/lib/python2.7/dist-packages/pycec/__main__.py", line 21
    yield from asyncio.sleep(10, loop=loop)
             ^
SyntaxError: invalid syntax
pi@rpihut:~ $ 
````

Any hint to debug this further?
Thanks

**Comment by Yannik25** [comment]
try running
`pip3 uninstall cec`

**Comment by konikvranik** [comment]
Yes, configuring libcec on RPi was a little bit tricky for me too. Look for tutorials linked from README.

**Comment by slv-009** [comment]
@danito, did you manage to fix this message? I have the same issue on a clean install on Raspian. Also run pip3 uninstall cec , but it confirmed it's not installed.... I really would like to get this working, but I am struggling. Any assistance will be appreciated.
