### ISSUE TITLE
Installation clarification

### ISSUE THREAD

**Issue by tinmice** [konikvranik/pyCEC#50]
I've compiled and installed libcec as per these instructions:
https://github.com/Pulse-Eight/libcec/blob/master/docs/README.raspberrypi.md

However, running `python3 -m pycec` returns the following error.

```
pi@raspberrypi:~/libcec/build $ python3 -m pycec
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/.local/lib/python3.5/site-packages/pycec/__main__.py", line 164, in <module>
    main()
  File "/home/pi/.local/lib/python3.5/site-packages/pycec/__main__.py", line 32, in main
    network = HDMINetwork(CecAdapter("pyCEC", activate_source=False),
  File "/home/pi/.local/lib/python3.5/site-packages/pycec/cec.py", line 20, in __init__
    import cec
ImportError: No module named 'cec'
```

Probably not a bug but I'm missing something in the install process.

**Comment by codymhorton** [comment]
I agree I mentioned this here: https://github.com/konikvranik/pyCEC/issues/51#issuecomment-421459525. It installs in 2.7 packages not 3 but pycec looks to be written for python3.

**Comment by codymhorton** [comment]
So if you use this commit on the upstream libcec: https://github.com/Pulse-Eight/libcec/pull/409/commits/feacdd32ce458f31752606e904b8cc4e3c8487a3 it should work at least it did for me. So instead of cloning the official libcec you can clone the author of that commit or just apply the changes he made to the official one.

**Comment by FreezeFiver** [comment]
To compile on Raspberry Pi, the steps given by [libcec](https://github.com/Pulse-Eight/libcec/blob/master/docs/README.raspberrypi.md) seems to be 90% correct after all, and there's no need to compile from a fork or a specific commit.

The 10% is: the `cmake` process searches for Python lib as they were installed. If you follow the [README](https://github.com/Pulse-Eight/libcec/blob/master/docs/README.raspberrypi.md) literally, you'd `apt install` a `python-dev`, which is really python 2.

Instead, you should `apt install python3-dev`. After do so, `cmake` would find proper python 3.x lib, and be set up to build for python 3.
